name: Parent Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-child-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Child Pipeline
      id: trigger
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: child_workflow.yml
        token: ${{ secrets.TOKEN }}
        repo: ambarih/trivy
    
    - name: Wait for Child Pipeline
      run: |
        sleep 120
        for i in {1..10}; do
          status=$(curl -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ambarih/trivy/actions/runs \
            | jq -r '.workflow_runs | map(select(.name == "Child Pipeline" and .head_branch == "main")) | .[0].conclusion')
          if [[ "$status" == "success" ]]; then
            echo "Child pipeline succeeded."
            exit 0
          elif [[ "$status" == "failure" ]]; then
            echo "Child pipeline failed."
            exit 1
          fi
          sleep 24
        done
        echo "Child pipeline did not complete in time."
        exit 1
